### PR TITLE
Add ability to comment with CMD + /

### LINKED ISSUE #2: Cannot use "Ctrl + /" to comment a block of code
As described in the title, it is not possible to comment a block of code by using "Ctrl + /" shortcut convention of Sublime Text.

Best,

### PR DESCRIPTION
**Pull request by quicksnap**
Resolve #2 and makes my life better =)

### CODE REVIEW

**Comment by joshuawarner32** [comment]
Whoops!  Would have been good to check for an existing PR before filing my own (#4).  The only difference is I also added a handler for the alternate comments (cmd+shift+/, `/* comment */`).  @quicksnap, I'm fine with closing mine if you want.

@kingofmalkier, any idea when we can get this merged, before anyone else duplicates this effort? ;)

**Comment by quicksnap** [comment]
@joshuawarner32 which ever PR is better (probably yours!) is best to merge in. I don't care about PR stats =P

It would be nice to have it go into master, though!

**Comment by kingofmalkier** [comment]
Sorry for the delay! New baby, excuses, I am lame, etc.

@joshuawarner32, your PR is the more fully featured one, so I'll accept that and close this one.

@quicksnap, I still greatly appreciate the effort, and apologize that I didn't accept this, umm, months ago.

**Comment by quicksnap** [comment]
Awesome! Glad to hear the commenting is upstream. Congrats on having a life away from GitHub! =P

**Comment by kingofmalkier** [comment]
Thanks! I just pulled the updated plugin (2.1.0) using package control and commenting works like a charm. Definitely a nice little feature to add.

**Pull request closed without merging**
